### ISSUE TITLE
Evaluation standard of Meiten is not obvious.

### ISSUE THREAD

**Issue by shogochiai** [sjntn/meiten#4]
When a committer try contributing, there's no way to decide whether "This shop should called Meiten or not."

For gathering the help of local committer, contributing environment should be enhanced (IMHO)

Best, 🍣

**Comment by sjntn** [comment]
It seems to me Meiten(great restaurant) isn't needed defined because it get hard to contribute this repository if we define it as something. I'd just like to know Meiten they regard!

**Comment by shogochiai** [comment]
Okay, I'll follow you.
